/* Generated by wayland-scanner 1.25.0 */

#ifndef FIFO_V1_SERVER_PROTOCOL_H
#define FIFO_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_fifo_v1 The fifo_v1 protocol
 * @section page_ifaces_fifo_v1 Interfaces
 * - @subpage page_iface_wp_fifo_manager_v1 - protocol for fifo constraints
 * - @subpage page_iface_wp_fifo_v1 - fifo interface
 * @section page_copyright_fifo_v1 Copyright
 * <pre>
 *
 * Copyright © 2023 Valve Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_surface;
struct wp_fifo_manager_v1;
struct wp_fifo_v1;

#ifndef WP_FIFO_MANAGER_V1_INTERFACE
#define WP_FIFO_MANAGER_V1_INTERFACE
/**
 * @page page_iface_wp_fifo_manager_v1 wp_fifo_manager_v1
 * @section page_iface_wp_fifo_manager_v1_desc Description
 *
 * When a Wayland compositor considers applying a content update, it must
 * ensure all the update's readiness constraints are met. This protocol adds
 * completion of a display refresh cycle as a readiness constraint.
 * @section page_iface_wp_fifo_manager_v1_api API
 * See @ref iface_wp_fifo_manager_v1.
 */
/**
 * @defgroup iface_wp_fifo_manager_v1 The wp_fifo_manager_v1 interface
 *
 * When a Wayland compositor considers applying a content update, it must
 * ensure all the update's readiness constraints are met. This protocol adds
 * completion of a display refresh cycle as a readiness constraint.
 */
extern const struct wl_interface wp_fifo_manager_v1_interface;
#endif
#ifndef WP_FIFO_V1_INTERFACE
#define WP_FIFO_V1_INTERFACE
/**
 * @page page_iface_wp_fifo_v1 wp_fifo_v1
 * @section page_iface_wp_fifo_v1_desc Description
 *
 * Adds display refresh constraints to content updates for one surface.
 * @section page_iface_wp_fifo_v1_api API
 * See @ref iface_wp_fifo_v1.
 */
/**
 * @defgroup iface_wp_fifo_v1 The wp_fifo_v1 interface
 *
 * Adds display refresh constraints to content updates for one surface.
 */
extern const struct wl_interface wp_fifo_v1_interface;
#endif

#ifndef WP_FIFO_MANAGER_V1_ERROR_ENUM
#define WP_FIFO_MANAGER_V1_ERROR_ENUM
enum wp_fifo_manager_v1_error {
	/**
	 * fifo manager already exists for surface
	 */
	WP_FIFO_MANAGER_V1_ERROR_ALREADY_EXISTS = 0,
};
#endif /* WP_FIFO_MANAGER_V1_ERROR_ENUM */

#ifndef WP_FIFO_MANAGER_V1_ERROR_ENUM_IS_VALID
#define WP_FIFO_MANAGER_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_wp_fifo_manager_v1
 * Validate a wp_fifo_manager_v1 error value.
 *
 * @return true on success, false on error.
 * @ref wp_fifo_manager_v1_error
 */
static inline bool
wp_fifo_manager_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case WP_FIFO_MANAGER_V1_ERROR_ALREADY_EXISTS:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* WP_FIFO_MANAGER_V1_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_wp_fifo_manager_v1
 * @struct wp_fifo_manager_v1_interface
 */
struct wp_fifo_manager_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 */
	void (*get_fifo)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t id,
			 struct wl_resource *surface);
};


/**
 * @ingroup iface_wp_fifo_manager_v1
 */
#define WP_FIFO_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_wp_fifo_manager_v1
 */
#define WP_FIFO_MANAGER_V1_GET_FIFO_SINCE_VERSION 1

#ifndef WP_FIFO_V1_ERROR_ENUM
#define WP_FIFO_V1_ERROR_ENUM
enum wp_fifo_v1_error {
	/**
	 * the associated surface no longer exists
	 */
	WP_FIFO_V1_ERROR_SURFACE_DESTROYED = 0,
};
#endif /* WP_FIFO_V1_ERROR_ENUM */

#ifndef WP_FIFO_V1_ERROR_ENUM_IS_VALID
#define WP_FIFO_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_wp_fifo_v1
 * Validate a wp_fifo_v1 error value.
 *
 * @return true on success, false on error.
 * @ref wp_fifo_v1_error
 */
static inline bool
wp_fifo_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case WP_FIFO_V1_ERROR_SURFACE_DESTROYED:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* WP_FIFO_V1_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_wp_fifo_v1
 * @struct wp_fifo_v1_interface
 */
struct wp_fifo_v1_interface {
	/**
	 * sets the start point for a fifo constraint
	 *
	 * The barrier becomes active with the wl_surface commit
	 * containing this request and clears after the following
	 * non-tearing latching deadline.
	 */
	void (*set_barrier)(struct wl_client *client,
			    struct wl_resource *resource);
	/**
	 * adds a fifo constraint to a content update
	 *
	 * The wl_surface commit containing this request is not ready
	 * while the previously installed fifo barrier is active.
	 */
	void (*wait_barrier)(struct wl_client *client,
			     struct wl_resource *resource);
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_wp_fifo_v1
 */
#define WP_FIFO_V1_SET_BARRIER_SINCE_VERSION 1
/**
 * @ingroup iface_wp_fifo_v1
 */
#define WP_FIFO_V1_WAIT_BARRIER_SINCE_VERSION 1
/**
 * @ingroup iface_wp_fifo_v1
 */
#define WP_FIFO_V1_DESTROY_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
