import CoreVideo
import IOSurface
import XCTest
import NativePipeProtocol
@testable import NativePipeRemote

final class H264HardwareTests: XCTestCase {
    private func fixture() throws -> [(MediaWire.Header, Data)] {
        guard let path = ProcessInfo.processInfo.environment["NATIVEPIPE_TEST_NVENC_FIXTURE"] else {
            throw XCTSkip("Opt-in fixture generated by the real NVENC encoder test")
        }
        let packets = MediaWire.Demuxer().push(try Data(contentsOf: URL(fileURLWithPath: path)))
        XCTAssertEqual(packets.filter { $0.0.codec != .alphaRLE }.count, 95)
        return packets
    }

    func testHardwareCapabilityIsPassedBeforeRemoteApplicationStarts() {
        let command = SSHCommand(destination: "test", application: ["true"])
        let enabled = command.makeRemoteScript(uploadCompositor: false, hardwareH264: true)
        let disabled = command.makeRemoteScript(uploadCompositor: false, hardwareH264: false)
        XCTAssertTrue(enabled.contains("export NATIVEPIPE_HOST_H264_HARDWARE=1\n"))
        XCTAssertTrue(disabled.contains("export NATIVEPIPE_HOST_H264_HARDWARE=0\n"))
        XCTAssertLessThan(enabled.range(of: "export NATIVEPIPE_HOST_H264_HARDWARE")!.lowerBound,
                          enabled.range(of: "exec ")!.lowerBound)
    }

    func testNVENCColorsInterframesResizeAndHardwareDecoder() throws {
        let packets = try fixture().filter { $0.0.codec == .h264 }
        XCTAssertEqual(packets.count, 94)
        XCTAssertTrue(H264Decoder.hardwareAvailable)
        let decoder = H264Decoder()
        var frames = 0, failures = 0, retained: CVPixelBuffer?, original: [UInt8] = []
        var samples: [Double] = []
        decoder.onFailure = { _ in failures += 1 }
        for (header, bytes) in packets {
            XCTAssertNotEqual(header.flags & MediaWire.flagHardwareEncoded, 0)
            decoder.onFrame = { id, pixel in
                XCTAssertEqual(id, header.resourceID)
                XCTAssertEqual(CVPixelBufferGetWidth(pixel), Int(header.width))
                XCTAssertEqual(CVPixelBufferGetHeight(pixel), Int(header.height))
                // Sample interiors: 4:2:0 chroma intentionally mixes colors at
                // a moving edge, so its last colored pixel is not a color oracle.
                let offset = Int(id - 1) * 7 % 240
                let p = Self.sample(pixel, x: (40 - offset + 240) % 240)
                let background = Self.sample(pixel, x: (160 - offset + 240) % 240)
                for (actual, expected) in zip(p.prefix(3) + background.prefix(3), [220,180,40,30,18,10]) {
                    XCTAssertEqual(Int(actual), expected, accuracy: 20, "frame \(id)")
                }
                if retained == nil { retained = pixel; original = Self.sample(pixel) }
                frames += 1
            }
            let start = ProcessInfo.processInfo.systemUptime
            autoreleasepool {
                decoder.decode(annexB: bytes, width: Int(header.width), height: Int(header.height),
                    bitstreamEpoch: header.bitstreamEpoch, resourceID: header.resourceID, requireHardware: true)
            }
            XCTAssertTrue(decoder.usingHardware, "No software decoder may satisfy this test")
            if header.resourceID > 10 && header.resourceID <= 90 {
                samples.append((ProcessInfo.processInfo.systemUptime - start) * 1000)
            }
        }
        XCTAssertEqual(frames, 94); XCTAssertEqual(failures, 0)
        XCTAssertEqual(Self.sample(try XCTUnwrap(retained)), original)
        samples.sort()
        XCTAssertEqual(samples.count, 80)
        print("H264_PRODUCTION_DECODE hardware_frames=\(frames) mean_ms=\(samples.reduce(0,+)/Double(samples.count)) p50_ms=\(samples[40]) p95_ms=\(samples[75]) max_ms=\(samples.last!)")
        // A network header with a wrong size must not reuse a valid old session.
        let first = try XCTUnwrap(packets.first)
        decoder.decode(annexB: first.1, width: 1654, height: 1258,
            bitstreamEpoch: 100, resourceID: 100, requireHardware: true)
        XCTAssertEqual(failures, 1); XCTAssertEqual(frames, 94)
    }

    @MainActor func testNVENCStreamAlphaCodecSwitchesAndRetainedPixels() async throws {
        let packets = try fixture(), source = RemoteFrameSource()
        var failures: [String] = []
        source.onFailure = { failures.append($0) }
        defer { source.removeAll() }
        var retained: IOSurfaceRef?, original: [UInt8] = []
        for (header, bytes) in packets {
            XCTAssertTrue(source.ingest(header: header, payload: bytes))
            if header.codec == .alphaRLE { continue }
            let deadline = Date().addingTimeInterval(5)
            while !source.isResourcePublished(header.resourceID), failures.isEmpty, Date() < deadline {
                try await Task.sleep(for: .milliseconds(2))
            }
            XCTAssertTrue(failures.isEmpty, failures.joined(separator: "\n"))
            let surface = try XCTUnwrap(source.surface(forResource: header.resourceID))
            XCTAssertEqual(IOSurfaceGetWidth(surface), Int(header.width))
            XCTAssertEqual(IOSurfaceGetHeight(surface), Int(header.height))
            IOSurfaceLock(surface, .readOnly, nil)
            let p = IOSurfaceGetBaseAddress(surface).assumingMemoryBound(to: UInt8.self)
            XCTAssertEqual(p[3], header.resourceID == 95 ? 128 : 0)
            let sample = Array(UnsafeBufferPointer(start: p, count: 4))
            IOSurfaceUnlock(surface, .readOnly, nil)
            if retained == nil { retained = surface; original = sample }
        }
        let counts = source.decoderFrameCounts
        XCTAssertEqual(counts.hardware, 94); XCTAssertEqual(counts.software, 1)
        let old = try XCTUnwrap(retained)
        IOSurfaceLock(old, .readOnly, nil)
        XCTAssertEqual(Array(UnsafeBufferPointer(start: IOSurfaceGetBaseAddress(old).assumingMemoryBound(to: UInt8.self), count: 4)), original)
        IOSurfaceUnlock(old, .readOnly, nil)
        print("H264_PIPELINE hardware=\(counts.hardware) software_fallback=\(counts.software) alpha_resize_lifetime=PASS")
    }

    private static func sample(_ pixel: CVPixelBuffer, x: Int = 40) -> [UInt8] {
        CVPixelBufferLockBaseAddress(pixel, .readOnly)
        defer { CVPixelBufferUnlockBaseAddress(pixel, .readOnly) }
        let p = CVPixelBufferGetBaseAddress(pixel)!.advanced(by: 30 * CVPixelBufferGetBytesPerRow(pixel) + x * 4)
            .assumingMemoryBound(to: UInt8.self)
        return Array(UnsafeBufferPointer(start: p, count: 4))
    }
}
